/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { Hola, HolaInterface } from "../../contracts/Hola";

const _abi = [
  {
    inputs: [],
    name: "saludar",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b506101738061001f6000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c80638aa5915214610030575b600080fd5b61003861004e565b604051610045919061011b565b60405180910390f35b60606040518060400160405280600581526020017f486f6c6121000000000000000000000000000000000000000000000000000000815250905090565b600081519050919050565b600082825260208201905092915050565b60005b838110156100c55780820151818401526020810190506100aa565b60008484015250505050565b6000601f19601f8301169050919050565b60006100ed8261008b565b6100f78185610096565b93506101078185602086016100a7565b610110816100d1565b840191505092915050565b6000602082019050818103600083015261013581846100e2565b90509291505056fea264697066735822122060225e65d6aecef79b313d56a97b3dd0130676c35b7ce3507d89e6333a13496f64736f6c634300081c0033";

type HolaConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: HolaConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Hola__factory extends ContractFactory {
  constructor(...args: HolaConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(overrides?: Overrides & { from?: string }): Promise<Hola> {
    return super.deploy(overrides || {}) as Promise<Hola>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: string }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): Hola {
    return super.attach(address) as Hola;
  }
  override connect(signer: Signer): Hola__factory {
    return super.connect(signer) as Hola__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): HolaInterface {
    return new utils.Interface(_abi) as HolaInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): Hola {
    return new Contract(address, _abi, signerOrProvider) as Hola;
  }
}
