/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Hola__factory } from "./Hola__factory";
export { Lock__factory } from "./Lock__factory";
export { MockERC20__factory } from "./MockERC20__factory";
