/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../common";

export interface HolaInterface extends utils.Interface {
  functions: {
    "saludar()": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "saludar"): FunctionFragment;

  encodeFunctionData(functionFragment: "saludar", values?: undefined): string;

  decodeFunctionResult(functionFragment: "saludar", data: BytesLike): Result;

  events: {};
}

export interface Hola extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: HolaInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    saludar(overrides?: CallOverrides): Promise<[string]>;
  };

  saludar(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    saludar(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    saludar(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    saludar(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
